### the dimension of the matrix is determined by the number of square brackets

In [2]:
import numpy as np
twoD = np.array([[1,2,3],[4,5,6]])
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(threeD)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Eigenvalues and Eigenvectors

In [ ]:
A=np.array([[2,1],[1,2]])
e_val,e_vec=np.linalg.eig(A)
print("Eigenvalue is: ")
print("Eigenvector is")