## Comparing Iterative Methods

In [77]:
import numpy as np
import time
def jacobi(A, b, x0, tol, max_iterations):
    start=time.perf_counter()
    n = len(b)
    x = x0.copy()
    #print(x)
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            timer=time.perf_counter()-start
            return x_new, k,timer
        x = x_new
        #print(x)
    
    timer=time.perf_counter()-start
    return x, max_iterations,timer

def gauss_seidel(A, b, x0, tol, max_iterations):
    start=time.perf_counter()
    n = len(b)
    x = x0.copy()
    #print(x)
    
    for k in range(max_iterations):
        x_new = x.copy()
        
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
            # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            timer=time.perf_counter()-start
            return x_new, k,timer
        x = x_new
        #print(x)
    
    timer=time.perf_counter()-start
    return x, max_iterations,timer

In [78]:
from numpy.random import default_rng
rng=default_rng(2)

A=([[10,1,2,3,1],
    [1,12,1,2,3],
    [2,1,14,1,2],
    [3,2,1,15,1],
    [1,3,2,1,16]])
B=([[2,4,5,3,6],
    [3,1,4,5,2],
    [6,2,3,4,1],
    [5,3,6,2,4],
    [4,6,2,5,3]])
b=rng.random(4)
x0=np.zeros_like(b)
tol=1e-6
maxi=100
print(b)

[0.26161213 0.29849114 0.81422574 0.09191594]


In [86]:
solution,itAJ,tAJ=jacobi(A,b,x0,tol,maxi)
print("Iterations using Jacobi for A: ",itAJ)
print("It took ",tAJ," seconds")

solution,itBJ,tBJ=jacobi(B,b,x0,tol,maxi)
print("Iterations using Jacobi for B: ",itBJ)
print("It took ",tBJ," seconds")

solution,itAG,tAG=gauss_seidel(A,b,x0,tol,maxi)
print("Iterations using Gauss for A: ",itAG)
print("It took ",tAG," seconds")

solution,itBG,tBG=gauss_seidel(B,b,x0,tol,maxi)
print("Iterations using Gauss for B: ",itBG)
print("It took ",tBG," seconds")

Iterations using Jacobi for A:  12
It took  0.002031337469816208  seconds
Iterations using Jacobi for B:  100
It took  0.008998792618513107  seconds
Iterations using Gauss for A:  5
It took  0.0005444679409265518  seconds
Iterations using Gauss for B:  100
It took  0.007709834724664688  seconds


## Challenge 6a

In [99]:
D=np.array([[10,-1,2,0,0],
            [-1,11,-1,3,0],
            [2,-1,10,-1,0],
            [0,3,-1,8,-2],
            [0,0,0,-2,9]])
d=np.array([14,30,26,25,37])

x0D=np.zeros_like(d)
tolD=1e-6
maxiD=1000
print(d)

[14 30 26 25 37]


In [100]:
solution,itDJ,tDJ=jacobi(D,d,x0D,tolD,maxiD)
print("Iterations using Jacobi for C: ",itDJ)
print("It took ",tDJ," seconds")

solution,itDG,tDG=gauss_seidel(D,d,x0D,tolD,maxiD)
print("Iterations using Gauss for B: ",itDG)
print("It took ",tDG," seconds")

Iterations using Jacobi for C:  1
It took  0.0013906639069318771  seconds
Iterations using Gauss for B:  2
It took  0.00042484886944293976  seconds


## Challenge 6b

In [101]:
C=np.array([[1,2,3,0,0],
            [2,1,2,3,0],
            [3,2,1,2,3],
            [0,3,2,1,2],
            [0,0,3,2,1]])
c=np.array([14,22,33,26,22])

x0C=np.zeros_like(c)
tolC=1e-6
maxiC=1000
print(c)

[14 22 33 26 22]


In [103]:
solution,itCJ,tCJ=jacobi(C,c,x0C,tolC,maxiC)
print("Iterations using Jacobi for C: ",itCJ)
print("It took ",tCJ," seconds")
#The test failed, it did not converge

solution,itCG,tCG=gauss_seidel(C,c,x0C,tolC,maxiC)
print("Iterations using Gauss for B: ",itCG)
print("It took ",tCG," seconds")
#The test failed, it did not converge

Iterations using Jacobi for C:  1000
It took  0.07368573918938637  seconds
Iterations using Gauss for B:  1000
It took  0.055319247767329216  seconds


<ipython-input-77-cf82f6832fd7>:11: RuntimeWarning: overflow encountered in long_scalars
  s = sum(A[i][j] * x[j] for j in range(n) if j != i)
<ipython-input-77-cf82f6832fd7>:33: RuntimeWarning: overflow encountered in long_scalars
  s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
<ipython-input-77-cf82f6832fd7>:34: RuntimeWarning: overflow encountered in long_scalars
  s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
<ipython-input-77-cf82f6832fd7>:35: RuntimeWarning: overflow encountered in long_scalars
  x_new[i] = (b[i] - s1 - s2) / A[i][i]
